server {
    listen ${PORT};
    server_name localhost;

    # Fix: Include standard mime.types inside this block so CSS and other formats aren't wiped out
    types {
        include /etc/nginx/mime.types;
        application/manifest+json webmanifest;
    }

    # If a file extension is completely unknown, make HTML the default
    default_type text/html;

    location = /manifest.webmanifest {
        root /usr/share/nginx/html;
    }
