// Central site config + tool registry. Drives Header dropdown, Homepage grid,
// Tools index, footer links, and SEO canonical builder.
export const SITE = {
  name: "TopMoneyTools",
  tagline: "Navigating the private wealth landscape.",
  baseUrl: "https://topmoneytools.com",
  defaultDescription:
      "Free financial calculators and plain-English guides covering inflation, debt, mortgages, retirement, budgeting, net worth, and more. Calculator inputs run in your browser. Supported by advertising as described in Privacy.",
  };

// Live calculator registry (DSExpansion). Keep in sync with App.jsx routes.
export const TOOLS = [
  { slug: "food-inflation", num: "01", name: "Food Inflation Calculator", short: "See how rising grocery prices compound over time." },
  { slug: "debt-cost", num: "02", name: "Debt Cost Calculator", short: "Understand the true cost of any loan with amortization." },
  { slug: "mortgage-payment", num: "03", name: "Mortgage Payment Calculator", short: "Project monthly payment, total interest, and lifetime cost." },
  { slug: "investment-growth", num: "04", name: "Investment Growth Calculator", short: "Project compounding returns on regular contributions." },
  { slug: "retirement", num: "05", name: "Retirement Savings Calculator", short: "Map your runway and projected nest egg." },
  { slug: "budget-planner", num: "06", name: "Budget Planner", short: "Split income into needs, wants, and surplus." },
  { slug: "net-worth", num: "07", name: "Net Worth Calculator", short: "Assets minus liabilities — your net position." },
  { slug: "savings-goal", num: "08", name: "Savings Goal Calculator", short: "Find the timeline and monthly rate to reach any goal." },
  { slug: "emergency-fund", num: "09", name: "Emergency Fund Calculator", short: "See how many months of expenses your savings cover — and what's missing." },
  { slug: "savings-rate", num: "10", name: "Savings Rate Calculator", short: "Measure the share of income you keep — the habit behind every goal." },
  { slug: "tax-brackets", num: "11", name: "Tax Bracket Visualizer", short: "See exactly how progressive tax brackets apply to your income." },
  { slug: "rent-vs-buy", num: "12", name: "Rent vs. Buy Calculator", short: "Compare the full financial picture of renting versus buying a home." },
  { slug: "credit-card-payoff", num: "13", name: "Credit Card Payoff Calculator", short: "See how long it takes to clear your balance and the interest you'll pay." },
  { slug: "compound-interest", num: "14", name: "Compound Interest Visualizer", short: "Watch your money grow with contributions, earnings, and time." },
  { slug: "home-affordability", num: "15", name: "Home Affordability Calculator", short: "Find out how much house you can actually afford." },
  { slug: "auto-loan", num: "16", name: "Auto Loan Calculator", short: "Calculate monthly payments and total cost of your next car." },
  { slug: "retirement-withdrawal", num: "17", name: "Retirement Withdrawal Calculator", short: "Test if your savings will last through retirement." },
  { slug: "student-loan", num: "18", name: "Student Loan Repayment Calculator", short: "Map out your path to being debt-free from student loans." },
  { slug: "dca-vs-lump-sum", num: "19", name: "DCA vs. Lump Sum Simulator", short: "Compare dollar-cost averaging against investing all at once." },
  { slug: "insurance-gap", num: "20", name: "Insurance Gap Analyzer", short: "Find out if you have enough coverage to protect your family." },
  { slug: "net-worth-projection", num: "21", name: "Net Worth Projection Tool", short: "See your future net worth based on your current savings rate." },
  { slug: "fire-number", num: "22", name: "FIRE Number Calculator", short: "Calculate your Financial Independence number and timeline." },
];

export const LIVE_TOOLS = TOOLS;
export const TOOL_COUNT = TOOLS.length;

export const NAV_LINKS = [
  { label: "Education", path: "/education" },
  { label: "Glossary", path: "/glossary" },
  { label: "Resources", path: "/resources" },
  { label: "About", path: "/about" },
  { label: "The Editor", path: "/the-editor" },
  { label: "Contact", path: "/contact" },
  { label: "Full Directory", path: "/full-directory" },
];

// Glossary terms covering all tools and education articles
export const GLOSSARY = [
  ["inflation", "Inflation", "The rate at which prices rise over time — so the same money buys less in the future than today."],
  ["interest", "Interest", "What lenders charge (or pay) for using money, expressed as a yearly percentage — the interest rate."],
  ["compound-growth", "Compound Growth", "When earnings earn their own earnings. Each year's growth builds on the previous total."],
  ["net-worth", "Net Worth", "Everything you own (assets) minus everything you owe (liabilities). One number for financial health."],
  ["amortization", "Amortization", "How a loan is paid down over time. Early payments are mostly interest; later payments are mostly principal."],
  ["risk-tolerance", "Risk Tolerance", "How much investment volatility you can stomach emotionally and financially."],
  ["purchasing-power", "Purchasing Power", "How much your money actually buys. Inflation erodes purchasing power over time."],
  ["apr", "APR", "Annual Percentage Rate — the yearly cost of borrowing, including fees, used to compare loans."],
  ["credit-score", "Credit Score", "A number estimating how reliably you repay borrowed money. Higher scores unlock better rates."],
  ["principal", "Principal", "The original amount borrowed or invested, before interest."],
  ["balance", "Balance", "The remaining amount owed or held at any point in time."],
  ["term", "Term", "The length of a loan or investment, usually in years or months."],
  ["down-payment", "Down Payment", "The upfront cash you pay toward a purchase — reducing what you need to borrow."],
  ["equity", "Equity", "The portion of an asset you actually own: market value minus any loan against it."],
  ["liquidity", "Liquidity", "How quickly an asset can be turned into cash without losing value."],
  ["asset", "Asset", "Anything you own that has monetary value — cash, investments, property, vehicles."],
  ["liability", "Liability", "Anything you owe — mortgage, loans, credit card balances, unpaid bills."],
  ["budget", "Budget", "A plan for how income gets split across needs, wants, and savings."],
  ["surplus", "Surplus", "Income left over after all needs and wants are met — money available to save or invest."],
  ["deficit", "Deficit", "When spending exceeds income over a period."],
  ["savings-rate", "Savings Rate", "The % of your income you keep rather than spend."],
  ["emergency-fund", "Emergency Fund", "Cash set aside for unexpected expenses — typically 3-6 months of expenses."],
  ["return", "Return", "The gain or loss on an investment, usually expressed as a percentage."],
  ["diversification", "Diversification", "Spreading investments across assets to reduce risk."],
  ["volatility", "Volatility", "How much an investment's value swings up and down over time."],
  ["annuity", "Annuity", "A series of equal payments made at regular intervals — e.g., a fixed monthly pension."],
  ["yield", "Yield", "The income an investment generates, such as interest or dividends, usually as a percentage."],
  ["principal-interest", "Principal & Interest", "The two parts of a loan payment — principal reduces debt, interest is the lender's fee."],
  ["4-percent-rule", "4% Rule", "A guideline: you can safely withdraw ~4% of retirement savings yearly for ~30 years."],
  ["cash-reserve", "Cash Reserve", "Liquid money set aside for immediate use — the accessible savings that form the heart of an emergency fund."],
  ["fixed-expenses", "Fixed Expenses", "Costs that stay the same each month — rent, loan payments, insurance — the baseline an emergency fund must cover."],
  ["variable-expenses", "Variable Expenses", "Costs that fluctuate month to month — groceries, utilities, dining — easier to trim than fixed costs."],
  ["financial-resilience", "Financial Resilience", "Your ability to weather shocks — job loss, medical bills, emergencies — without falling into debt."],
  ["discretionary-income", "Discretionary Income", "Income left after taxes and essential expenses — money available for wants, saving, or investing."],
  ["budgeting", "Budgeting", "The ongoing practice of splitting income across needs, wants, and savings — turning a budget into a habit."],
  ["withdrawal-rate", "Withdrawal Rate", "The percentage of your portfolio you spend each year in retirement."],
  ["safe-withdrawal-rate", "Safe Withdrawal Rate", "A conservative annual withdrawal percentage designed to make retirement savings last — the 4% Rule is the best-known example."],
  ["fire", "FIRE", "Financial Independence, Retire Early — a movement focused on aggressive saving to retire decades ahead of the traditional timeline."],
  ["dollar-cost-averaging", "Dollar-Cost Averaging", "Investing a fixed amount on a regular schedule regardless of price — buying more shares when cheap, fewer when expensive."],
  ["lump-sum", "Lump Sum", "A single, one-time payment or investment rather than spreading it over time."],
  ["side-hustle", "Side Hustle", "A secondary income stream outside of a primary job — freelancing, gig work, or a small business."],
  ["tax-bracket", "Tax Bracket", "A range of income taxed at a specific rate. Only the portion of income in each bracket is taxed at that rate — not your entire income."],
  ["progressive-tax", "Progressive Tax", "A tax system where the rate increases as income rises — higher earners pay a larger share of additional income."],
  ["student-loan", "Student Loan", "Money borrowed to pay for education, repaid over time with interest — federal and private options have different terms."],
  ["auto-loan", "Auto Loan", "A loan used to purchase a vehicle, typically repaid over 3–7 years with fixed monthly payments."],
  ["net-worth-by-age", "Net Worth by Age", "A benchmark showing typical net worth ranges for different age groups — useful for gauging progress, not for comparison."],
  ["couples-finance", "Couples and Money", "Strategies for managing shared finances — joint accounts, budgeting together, and navigating different money styles."],
  ["insurance-gap", "Insurance Gap", "The shortfall between the coverage you have and what you would actually need in a worst-case scenario."],
  ["financial-independence", "Financial Independence", "Having enough investments and passive income to cover living expenses without needing to work."],
  ["401k", "401(k)", "An employer-sponsored retirement account that lets you contribute pre-tax income, often with employer matching."],
  ["ira", "IRA", "Individual Retirement Account — a tax-advantaged account for retirement savings outside of employer plans."],
  ["roth-ira", "Roth IRA", "A retirement account funded with after-tax dollars — qualified withdrawals in retirement are tax-free."],
  ["compound-interest", "Compound Interest", "Interest earned on both the original principal and on accumulated interest from prior periods — earning interest on interest."],
  ["capital-gains", "Capital Gains", "Profit from selling an asset for more than its purchase price — taxed differently from ordinary income."],
  ["dividend", "Dividend", "A portion of a company's earnings paid to shareholders, usually quarterly — a source of investment income."],
  ["index-fund", "Index Fund", "A mutual fund or ETF that tracks a market index like the S&P 500 — low-cost, diversified, and passive."],
  ["etf", "ETF", "Exchange-Traded Fund — a basket of securities that trades on an exchange like a stock, offering instant diversification."],
  ["market-timing", "Market Timing", "Attempting to predict market movements to buy low and sell high — extremely difficult to do consistently."],
  ["refinancing", "Refinancing", "Replacing an existing loan with a new one, often to get a lower interest rate or different term."],
  ["credit-utilization", "Credit Utilization", "The percentage of your available credit that you're using — keeping it below 30% helps your credit score."],
  ["pmi", "PMI", "Private Mortgage Insurance — required when your down payment is less than 20% of the home price."],
  ["opportunity-cost", "Opportunity Cost", "What you give up when you choose one option over another — the value of the next-best alternative."],
  ["asset-allocation", "Asset Allocation", "How your portfolio is divided among stocks, bonds, and cash — the primary driver of long-term returns."],
  ["bear-market", "Bear Market", "A prolonged period of falling prices, typically a decline of 20% or more from recent highs."],
  ["bull-market", "Bull Market", "A sustained period of rising prices, typically gains of 20% or more from recent lows."],
  ["expense-ratio", "Expense Ratio", "The annual fee a fund charges to manage your money, expressed as a percentage of assets."],
  ["minimum-payment", "Minimum Payment", "The smallest amount you must pay on a credit card or loan each month to stay current."],
  ["grace-period", "Grace Period", "The time window after a billing cycle ends during which you can pay without incurring interest."],
  ["deductible", "Deductible", "The amount you pay out of pocket before insurance coverage kicks in."],
  ["rebalancing", "Rebalancing", "Adjusting your portfolio back to its target allocation by buying and selling assets."],
  ["pension", "Pension", "A retirement plan where an employer commits to paying a defined benefit for life."],
  ["debt-to-income", "Debt-to-Income Ratio", "Monthly debt payments divided by monthly gross income — a key metric lenders use to assess affordability."],
  ["mortgage", "Mortgage", "A loan used to buy real estate, where the property itself serves as collateral — typically repaid over 15–30 years."],
  ["interest-rate", "Interest Rate", "The percentage a lender charges for borrowing money, or the percentage earned on savings and investments."],
  ["bond", "Bond", "A loan you make to a government or corporation in exchange for regular interest payments and the return of principal at maturity."],
  ["stock", "Stock", "A share of ownership in a company — stocks represent a claim on the company's assets and earnings."],
  ["cpi", "CPI (Consumer Price Index)", "A basket of goods and services tracked by the government to measure inflation — the most widely used cost-of-living gauge."],
  ["cost-of-living", "Cost of Living", "How much it costs to maintain a certain standard of living — housing, food, transportation, healthcare, and taxes."],
  ["consumer-price-index", "Consumer Price Index", "The official U.S. government measure of inflation, tracking the average change in prices paid by urban consumers."],
  ["insurance", "Insurance", "A contract that transfers financial risk to a company in exchange for regular premium payments."],
  ["insurance-premium", "Insurance Premium", "The amount you pay — usually monthly or annually — to keep an insurance policy active."],
  ["hsa", "HSA (Health Savings Account)", "A tax-advantaged account for medical expenses, available only with high-deductible health plans — contributions, growth, and qualified withdrawals are all tax-free."],
  ["wage-growth", "Wage Growth", "The rate at which average wages increase over time — ideally outpacing inflation so purchasing power rises."],
  ["real-vs-nominal", "Real vs. Nominal", "Nominal values are the face-value numbers; real values adjust for inflation so you can compare purchasing power across time."],
  ["hard-inquiry", "Hard Inquiry", "A credit check that appears on your report when you apply for credit — too many can temporarily lower your score."],
  ["soft-inquiry", "Soft Inquiry", "A credit check that does not affect your score — used for pre-approvals, background checks, and checking your own credit."],
  ["payment-history", "Payment History", "The record of whether you paid past credit accounts on time — the single biggest factor in your credit score."],
  ["discretionary-spending", "Discretionary Spending", "Money spent on wants rather than needs — dining out, entertainment, travel, hobbies."],
  ["essential-expenses", "Essential Expenses", "Non-negotiable costs required for basic living — housing, food, utilities, healthcare, transportation."],
  ["loan-term", "Loan Term", "The length of time you have to repay a loan — longer terms mean lower monthly payments but more total interest."],
  ["income-protection", "Income Protection", "Insurance or savings strategies designed to replace your income if you can't work due to illness, injury, or job loss."],
].map(([slug, term, def]) => ({ slug, term, def }));