# Generate public/sitemap.xml from live App routes + Education ARTICLES + tools registry.
from pathlib import Path
import re
from datetime import date

ROOT = Path(__file__).resolve().parents[1]
TODAY = date.today().isoformat()

app = (ROOT / "src/App.jsx").read_text(encoding="utf-8")
edu = (ROOT / "src/pages/Education.jsx").read_text(encoding="utf-8")
site = (ROOT / "src/config/site.config.js").read_text(encoding="utf-8")

# Paths that are redirects only — omit from sitemap
REDIRECT_ONLY = {
    "/education/budgeting-for-beginners-50-30-20-rule-explained",
}

# Collect tool slugs from registry
tool_slugs = re.findall(r'slug:\s*"([^"]+)"', site)
# Only from TOOLS array roughly - site.config has glossary too with slug-like
# Better: TOOLS entries have num
tools = re.findall(r'\{\s*slug:\s*"([^"]+)",\s*num:', site)

article_slugs = re.findall(r'slug:\s*"([^"]+)"', edu)

# Static pages (indexable)
static = [
    ("/", 1.0, "weekly"),
    ("/start-here", 0.9, "weekly"),
    ("/tools", 0.9, "weekly"),
    ("/education", 0.9, "weekly"),
    ("/glossary", 0.8, "monthly"),
    ("/resources", 0.8, "monthly"),
    ("/full-directory", 0.8, "weekly"),
    ("/about", 0.7, "monthly"),
    ("/the-editor", 0.7, "monthly"),
    ("/contact", 0.6, "monthly"),
    ("/privacy", 0.5, "yearly"),
    ("/terms", 0.5, "yearly"),
    ("/disclaimer", 0.5, "yearly"),
]

BASE = "https://topmoneytools.com"


def url_entry(path: str, priority: float, freq: str) -> str:
    loc = BASE if path == "/" else f"{BASE}{path}"
    return (
        f"  <url>"
        f"<loc>{loc}</loc>"
        f"<lastmod>{TODAY}</lastmod>"
        f"<changefreq>{freq}</changefreq>"
        f"<priority>{priority:.1f}</priority>"
        f"</url>"
    )


lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    "  <!-- Auto-generated by scripts/gen-sitemap.py — do not hand-edit; regenerate. -->",
    "  <!-- Core -->",
]
for path, pri, freq in static:
    lines.append(url_entry(path, pri, freq))

lines.append("  <!-- Tools (01–22) -->")
for slug in tools:
    lines.append(url_entry(f"/tools/{slug}", 0.8, "weekly"))
lines.append(url_entry("/tools/how-our-calculators-work", 0.7, "monthly"))

lines.append("  <!-- Education (101–140) -->")
for slug in article_slugs:
    path = f"/education/{slug}"
    if path in REDIRECT_ONLY:
        continue
    lines.append(url_entry(path, 0.7, "monthly"))

lines.append("</urlset>")
lines.append("")

out = ROOT / "public/sitemap.xml"
out.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {out} with {sum(1 for l in lines if '<loc>' in l)} URLs")
print(f"  tools: {len(tools)} + how-our-calculators-work")
print(f"  articles: {len(article_slugs)}")
