name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: project-7ee9ba0e-6038-467d-83a
  SERVICE: topmoneytools-website
  REGION: northamerica-northeast1
  WIF_PROVIDER: projects/687832097444/locations/global/workloadIdentityPools/github-pool/providers/github-provider
  SERVICE_ACCOUNT: github-deploy-sa@project-7ee9ba0e-6038-467d-83a.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          project_id: ${{ env.PROJECT_ID }}
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          source: .
